#!/usr/bin/env sh

# ===== 基础 =====
yabai -m config mouse_follows_focus          on
yabai -m config focus_follows_mouse          off

yabai -m config window_placement             second_child
yabai -m config window_shadow                on

# ===== 自动平铺（关键）=====
yabai -m config layout                       bsp
yabai -m config auto_manage                  on
yabai -m config auto_balance                 on

# ===== 间距 =====
yabai -m config top_padding                  12
yabai -m config bottom_padding               12
yabai -m config left_padding                  12
yabai -m config right_padding                 12
yabai -m config window_gap                   10

# ===== 必须 float 的系统窗口 =====
yabai -m rule --add app="^Finder$"            manage=off
yabai -m rule --add role="AXSystemDialog"     manage=off
yabai -m rule --add subrole="AXDialog"        manage=off
yabai -m rule --add subrole="AXSystemDialog"  manage=off

# （不要动普通窗口，不要 float 标准窗口）
# （绝对不要写 subrole="AXStandardWindow" fullscreen=on）

# ===== 视觉 =====
yabai -m config window_animation_duration 0.20
yabai -m config window_opacity on
yabai -m config window_opacity_duration 0.18
yabai -m config active_window_opacity   1.0
yabai -m config normal_window_opacity   0.92

